// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fflgxanhzepqmwbyhhhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbGd4YW5oemVwcW13YnloaGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjI4NDIsImV4cCI6MjA2MTM5ODg0Mn0.ZPQfZfoDRETMHX2KZJMvE3ASM-ElPr6ZkdDhIyD8Qto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);